### PR TITLE
Provide humane-test-output

### PR DESCRIPTION
**Pull request by danielcompton**
This is a clone of humane-test-output's formatting code, translated to
ClojureScript.

This isn't ready to merge, it still has
- [ ] Align vertical columns for pretty printed output.
- [ ] Diff equality output

### CODE REVIEW

**Comment by honzabrecka** [comment]
Great idea, thanks! That will definitely be added.

**Comment by honzabrecka** [comment]
I updated karma dependency - if you rebase, tests on travis should pass. Do you plan to continue to work on this and integrate mentioned https://github.com/pjstadig/humane-test-output? They recently added [clojurescript support](https://github.com/pjstadig/humane-test-output/pull/9).

**Comment by danielcompton** [comment]
That's great, I think it probably makes sense to go back and look at what they have and how much can be used for karma-reporter. Not sure how much time I'll have to work on this in the next few weeks sorry.

**Comment by nenadalm** [comment]
Hi. I was looking for way to run tests in multiple browsers (currently they run only on phantomjs) and found this lib.

## Related to the reporting:
this test:
```cljs
(deftest map-test
  (is (= {:a "a"
          :b "b"}
         {:a "b"
          :b "b"})))
```
has value
```cljs
[{:file cljs$test$run_block@http, :line 365, :column 11, :type :fail, :expected (= {:a a, :b b} {:a b, :b b}), :actual (not (= {:a a, :b b} {:a b, :b b})), :message nil}]
```
for variable ```test-var-result``` (https://github.com/honzabrecka/karma-reporter/blob/a14e061c513affed7235c5a4380adcb510f1fda2/src/jx/reporter/karma.cljs#L49)

and value
```cljs
({:file nil, :line nil, :type :fail, :diffs ([{:a b, :b b} ({:a a} {:a b})]), :expected {:a a, :b b}, :actual ({:a b, :b b}), :message nil})
```
for ```args``` variable (https://github.com/pjstadig/humane-test-output/blob/40523c2b65a995dc38bdd18c759b6e3b6ef75d80/src/pjstadig/util.cljc#L92)

so it seems that if ```:expected``` ```:actual``` and ```:diff``` keys are fixed, then ```pjstadig.util/report-``` can be called instead of ```jx.reporter.karma/format-log```
(as the ```report-``` works with the keys https://github.com/pjstadig/humane-test-output/blob/40523c2b65a995dc38bdd18c759b6e3b6ef75d80/src/pjstadig/util.cljc#L35)

I might try to do this some day (just writing my thoughts and checks here if somebody was interested to make it faster :))

**Comment by honzabrecka** [comment]
I thought about it a little, and I don't know how to deal with the following ones:

```clojure
(is (= 1 2 3))
(is (true? false))
(is (my-variadic-comparator (foo) (bar) (baz)))
```

How the expected, actual and diff properties should look like in this cases?

**Comment by honzabrecka** [comment]
I added pretty printing https://github.com/honzabrecka/karma-reporter/commit/18479994c90a2b1be31a01409e4fc1cce275c4b9. Diff will continue.

**Comment by nenadalm** [comment]
Cool. I'll try to check if there is something in clojurescript repository https://github.com/clojure/clojurescript which would help to get data into the shape.

**Comment by nenadalm** [comment]
now I see where the ```:diffs``` came from https://github.com/pjstadig/humane-test-output/blob/40523c2b65a995dc38bdd18c759b6e3b6ef75d80/src/pjstadig/assert_expr.cljc#L15 :)

**Comment by nenadalm** [comment]
I've created pr here: https://github.com/honzabrecka/karma-reporter/pull/9/files (unfinished yet)

**Comment by danielcompton** [comment]
As you can tell, I haven't been too engaged with this lately... Happy for someone else to take whatever I've done that is useful.

**Comment by honzabrecka** [comment]
Finally done in master. Thanks for your thoughts/suggestions!

**Pull request closed without merging**
